/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wec.view;

import br.com.wec.dao.AgendaDAO;
import br.com.wec.model.Agenda;
import br.com.wec.model.Medico;
import br.com.wec.model.Paciente;
import java.awt.HeadlessException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Collection;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Beto
 */
public class JFrameNovaconsulta extends javax.swing.JFrame {

    AgendaDAO adao = new AgendaDAO();
    Collection<Medico> medicos;

    Collection<Paciente> pacientes;

    String HI = "08:00:00";
    String HF = "17:30:00";
    int DUR = 30;

    /**
     * Creates new form JFrameNovaconsulta
     */
    public JFrameNovaconsulta() {
        initComponents();
        preencheComboMedico();
        preencheComboPaciente();
        preencheHora();
        
        jclData.setMinSelectableDate(new Date());
    }

    private void preencheComboPaciente() {
        DefaultComboBoxModel cboPacientes = (DefaultComboBoxModel) cboPaciente.getModel();
        cboPacientes.removeAllElements();

        try {
            pacientes = adao.getListaPaciente();

            for (Paciente p : pacientes) {
                cboPacientes.addElement(p.getNome());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "combo" + ex.getMessage() + ex.getCause());
        }
    }

    private void preencheComboMedico() {
        DefaultComboBoxModel cboMedicos = (DefaultComboBoxModel) cboMedico.getModel();
        cboMedicos.removeAllElements();
        //Collection<Medico> pessoas;

        try {
            medicos = adao.getListaMedico();

            for (Medico m : medicos) {
                cboMedicos.addElement(m.getNome());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "combo" + ex.getMessage() + ex.getCause());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNovoAgendamento = new javax.swing.JLabel();
        jButtonSalvarAgendamento = new javax.swing.JButton();
        jLabelDataAgendamento = new javax.swing.JLabel();
        jLabelHoraAgendamento = new javax.swing.JLabel();
        jLabelPacienteAgendamento = new javax.swing.JLabel();
        jLabelMedicoAgendamento = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jclData = new com.toedter.calendar.JCalendar();
        cboHora = new javax.swing.JComboBox();
        cboDuracao = new javax.swing.JComboBox();
        cboMedico = new javax.swing.JComboBox();
        cboPaciente = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jdtGrid = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova Consulta");
        setBackground(new java.awt.Color(255, 255, 255));

        jLabelNovoAgendamento.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelNovoAgendamento.setText("Agendamento de Consultas");

        jButtonSalvarAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/wec/img/Save.png"))); // NOI18N
        jButtonSalvarAgendamento.setToolTipText("Salvar");
        jButtonSalvarAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarAgendamentoActionPerformed(evt);
            }
        });

        jLabelDataAgendamento.setText("Data");

        jLabelHoraAgendamento.setText("Hora:");

        jLabelPacienteAgendamento.setText("Paciente:");

        jLabelMedicoAgendamento.setText("Medico:");

        jLabelStatus.setText("Duração");

        jclData.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jclDataPropertyChange(evt);
            }
        });

        cboHora.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboHoraItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("3");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("5");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("6");

        jdtGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jdtGrid);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelPacienteAgendamento)
                                    .addComponent(cboPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMedicoAgendamento))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDataAgendamento)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jclData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelHoraAgendamento)
                                            .addComponent(cboHora, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelStatus))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(cboDuracao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonSalvarAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabelNovoAgendamento)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelNovoAgendamento)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(cboHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelHoraAgendamento)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelStatus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jButtonSalvarAgendamento)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDataAgendamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jclData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelMedicoAgendamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPacienteAgendamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarAgendamentoActionPerformed
        // TODO add your handling code here:

        java.util.Date dt = jclData.getDate();

        Agenda a = new Agenda();

        a.setData(new java.sql.Date(dt.getTime()));

        a.setDthora(new java.sql.Date(new Date().getTime()));

        /*
         *********************************
         **Pegar string da data atual*****
         *********************************
         */
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");

        Date today = jclData.getDate();

        String reportDate = df.format(today);

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String dateInString = reportDate + " " + cboHora.getSelectedItem().toString();

        Date date = new Date();

        try {
            date = formatter.parse(dateInString);

        } catch (ParseException ex) {
            Logger.getLogger(JFrameNovaconsulta.class.getName()).log(Level.SEVERE, null, ex);
        }

        /**
         * *****************************
         */
        a.setHi(new java.sql.Date(date.getTime()));

        /**
         * ****************
         * Duracao ****************
         */
        String h = "";
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(date);

        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        gc.add(Calendar.MINUTE, Integer.parseInt(cboDuracao.getSelectedItem().toString()));
        h = sdf.format(gc.getTime());

        dateInString = reportDate + " " + h;

        try {
            date = formatter.parse(dateInString);

        } catch (ParseException ex) {
            Logger.getLogger(JFrameNovaconsulta.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*
         ************************
         */

        a.setHf(new java.sql.Date(date.getTime()));

        a.setMedico(getIdMedico(cboMedico.getSelectedItem().toString()));
        a.setPaciente(getIdPaciente(cboPaciente.getSelectedItem().toString()));
        
        a.setStatus(1);

        try {
            adao.inserir(a);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        
        preencheGrid();
    }//GEN-LAST:event_jButtonSalvarAgendamentoActionPerformed

    private int getIdPaciente(String nome) {
        int id = 0;

        for (Paciente p : pacientes) {
            if (nome == p.getNome()) {
                id = p.getId();
            }
        }
        return id;
    }

    private int getIdMedico(String nome) {
        int id = 0;

        for (Medico m : medicos) {

            if (nome == m.getNome()) {
                id = m.getId();
            }

        }
        return id;
    }


    private void jclDataPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jclDataPropertyChange
        preencheGrid();
        
    }//GEN-LAST:event_jclDataPropertyChange

    private void preencheGrid() throws HeadlessException {
        //preencheHora();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        
        Date today = jclData.getDate();
        
        String reportDate = df.format(today);
        
        
        try {
            jdtGrid.setModel(adao.getListaAgenda(reportDate));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void preencheHora() {
        // TODO add your handling code here:
        cboHora.removeAllItems();

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String dateInString = "24/11/2014 " + HI;

        Date date = new Date();
        try {
            date = formatter.parse(dateInString);

        } catch (ParseException ex) {
            Logger.getLogger(JFrameNovaconsulta.class.getName()).log(Level.SEVERE, null, ex);
        }

        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(date);

        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        //System.out.println(sdf.format(gc.getTime()));

        //gc.add(Calendar.MINUTE, 30);
        //System.out.println(sdf.format(gc.getTime()));
        String h = "";
        int duracao = 30;

        while (!h.equals(HF)) {

            if (!h.equals("")) {

                gc.add(Calendar.MINUTE, DUR);

                duracao = duracao + 30;
            }

            h = sdf.format(gc.getTime());

            cboHora.addItem(h);
        }
    }

    private void cboHoraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboHoraItemStateChanged
        // TODO add your handling code here:

        cboDuracao.removeAllItems();

        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        String dateInString = "24/11/2014 " + cboHora.getSelectedItem().toString();

        Date date = new Date();
        try {
            date = formatter.parse(dateInString);

        } catch (ParseException ex) {
            Logger.getLogger(JFrameNovaconsulta.class.getName()).log(Level.SEVERE, null, ex);
        }

        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(date);

        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        System.out.println(sdf.format(gc.getTime()));

        //gc.add(Calendar.MINUTE, 30);
        //System.out.println(sdf.format(gc.getTime()));
        String h = "";
        int duracao = 30;

        while (!h.equals(HF)) {

            if (!h.equals("")) {

                gc.add(Calendar.MINUTE, DUR);

                duracao = duracao + 30;
            }

            h = sdf.format(gc.getTime());

            cboDuracao.addItem(duracao);
        }
    }//GEN-LAST:event_cboHoraItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameNovaconsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameNovaconsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameNovaconsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameNovaconsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameNovaconsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboDuracao;
    private javax.swing.JComboBox cboHora;
    private javax.swing.JComboBox cboMedico;
    private javax.swing.JComboBox cboPaciente;
    private javax.swing.JButton jButtonSalvarAgendamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelDataAgendamento;
    private javax.swing.JLabel jLabelHoraAgendamento;
    private javax.swing.JLabel jLabelMedicoAgendamento;
    private javax.swing.JLabel jLabelNovoAgendamento;
    private javax.swing.JLabel jLabelPacienteAgendamento;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JCalendar jclData;
    private javax.swing.JTable jdtGrid;
    // End of variables declaration//GEN-END:variables
}
